name: CI

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: Run unittests
        run: |
          pytest test/test.py 
      
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6

      - name: Determine Docker image tag
        id: image
        run: |
          IMAGE_TAG="${{ steps.branch-name.outputs.current_branch }}_${{ github.sha }}"
          echo "tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: docker build 
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-fast-api:${{ steps.image.outputs.tag }} .

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: docker push 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-fast-api:${{ steps.image.outputs.tag }}
      
    outputs:
        image_tag: ${{ steps.image.outputs.tag }}

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:    
      
      - name: deploy DEMO API
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVERS }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            API=$(docker ps -q -f name=api )
            [[ ! -z $API ]] && docker stop $API && docker rm $API
            docker run --name api -d -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/python-fast-api:${{ needs.ci.outputs.image_tag }}"
     