name: edteam-fastapi-demo

on:
  push:
    branches:
      - rama_sebas
      - develop
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Verificar el código
      - name: Checkout
        uses: actions/checkout@v3

      # Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Ejecutar pruebas
      - name: Run tests
        run: pytest tests/test.py

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      # Verificar el código
      - name: Checkout
        uses: actions/checkout@v3

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y subir la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sebaskrieg/edteam-fastapi-demo:latest
