name: edteam-fastapi-demo

on:
  push:
    branches:
      - rama_sebas
      - develop
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Verificar el código
      - name: Checkout
        uses: actions/checkout@v3

      # Instalar dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt 

      # Ejecutar pruebas
      - name: Run tests
        run: pytest test/test.py

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      # Verificar el código
      - name: Checkout
        uses: actions/checkout@v3

      # Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y subir la imagen Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: sebaskrieg/edteam-fastapi-demo:latest

#Comenzar con la implementación de la acción de CI/CD
  cd:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:

      - name: Conectarse de forma remota al servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Conexión exitosa"
            sleep 5
            API=$(docker ps -q -f name=edteam-fastapi-demo)
            if [ ! -z "$API" ]; then
              docker stop $API
              docker rm $API
            fi
            echo "Descargando imagen"
            docker pull sebaskrieg/edteam-fastapi-demo:latest
            docker run -d -p 80:8080 --name edteam-fastapi-demo sebaskrieg/edteam-fastapi-demo:latest