name: PR checks

on:
  - pull_request

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Lint with pylint
        run: |
          pip install pylint
          OUTPUT=$(pylint app/ --exit-zero)
          echo "MESSAGE=$OUTPUT" >> $GITHUB_ENV
      
      - name: Post result to PR
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          allow-repeats: false 
      - name: Install dependencies
        run: |
          pip3 install -r requirements.txt
      
      - name: Run unittests
        run: |
          pytest test/test.py
